name: cashback_feat
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.19.0
  provider: ^6.1.5
  # UI dependencides
  flutter_svg: ^2.1.0
  percent_indicator: ^4.2.5

flutter:
  uses-material-design: true
  generate: true # For Flutter localization

  assets:
    - assets/images/
    - assets/vector_gfx/
  
  fonts:
    # Source: https://alfont.com/sst-arabic-medium-3-arabic-font-download.html.
    - family: SST Arabic
      fonts:
        - asset: assets/fonts/SST-Arabic-Medium.ttf
